### ISSUE TITLE
"TypeError: NetworkError when attempting to fetch resource."

### ISSUE THREAD

**Issue by giddyhup** [alexander0042/alexander0042.github.io#1]
Great idea. Thanks for the service. I get a forbidden/403 response with my API key. Is the account already over its limit? Am I missing something?

https://api.pirateweather.net/forecast/{key}/43.000000,-75.000000

**Comment by xplusplus** [comment]
I'm seeing this issue as well. I just registered, and I shouldn't have gotten throttled yet. Each attempt to call the API results in a 403.

**Comment by alexander0042** [comment]
Thanks for pointing out this issue- I'm sorry that I missed it earlier!
The most likely reason here is the API subscription- it's really easy to miss this step, but you'll get a 403 without it. Can you check that when you go to <https://pirateweather.net/apis>, you're subscribed to the PirateForcast Beta stage? It should be a green button underneath the API name.

**Comment by giddyhup** [comment]
As far as I am concerned, my issue is solved as per the exchange via reddit. I leave this open for @xplusplus.

**Comment by xplusplus** [comment]
Ah, I was not subscribed. Now it works as expected. Thank you very much!

**Comment by giddyhup** [comment]
and thus I can close this.
